package br.com.estudos.algaworksESR.entidade;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.*;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.type.LocalDateTimeType;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;

//@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode
@Data
//@Builder
@DynamoDBTable(tableName = "usuario")
public class Usuario implements Serializable {

    private static final long serialVersionUID = 1L;

//    @Id
//    @GeneratedValue(generator = "UUID")
//    @GenericGenerator(
//            name = "UUID",
//            strategy = "org.hibernate.id.UUIDGenerator")
//    @Column(name = "id", updatable = false, nullable = false)
    @Id
    @DynamoDBHashKey(attributeName = "usuarioId")
    @DynamoDBAutoGeneratedKey
    @JsonIgnore
    private String usuarioId;

    @DynamoDBAttribute(attributeName = "name")
    @JsonProperty("name")
    private String name;

    @DynamoDBAttribute(attributeName = "email")
    @JsonProperty("email")
    private String email;

    @DynamoDBAttribute(attributeName = "senha")
    @JsonProperty("senha")
    private String senha;

    private LocalDateTime datadeCadastro = LocalDateTime.now();

}
